---
- name: Create the {{ asdf_user }} user
  user:
    name: "{{ asdf_user }}"
    shell: /bin/bash
    password: "*"
  become: true
  when: asdf_user_create

- name: Check if asdf is present
  shell: "test -x /home/{{ asdf_user }}/.asdf/bin/asdf"
  ignore_errors: yes
  register: asdf_present
  changed_when: false
  tags: asdf
  become: true
  become_user: "{{ asdf_user }}"

- include_tasks: asdf-deps-debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: asdf-deps-redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Download asdf
  get_url: url=https://github.com/asdf-vm/asdf/archive/v{{ asdf_version }}.tar.gz
           dest=/tmp/asdf-{{ asdf_version }}.tar.gz
  tags: asdf
  when: asdf_present is failed
  become: true
  become_user: "{{ asdf_user }}"

- name: Unpack asdf
  unarchive:
    src: /tmp/asdf-{{ asdf_version }}.tar.gz
    dest: "/home/{{ asdf_user }}/"
    remote_src: true
  tags: asdf
  when: asdf_present is failed
  become: true
  become_user: "{{ asdf_user }}"

- name: stat .asdf
  stat: path=/home/{{ asdf_user }}/.asdf
  register: asdf_stat
  tags: asdf
  become: true
  become_user: "{{ asdf_user }}"

- name: Move asdf-version to .asdf
  command: mv /home/{{ asdf_user }}/asdf-{{ asdf_version }} /home/{{ asdf_user }}/.asdf
  tags: asdf
  when: asdf_stat.stat.exists == false
  become: true
  become_user: "{{ asdf_user }}"

- name: stat .tool-versions
  stat: path=/home/{{ asdf_user }}/.tool-versions
  register: asdf_tool_versions_stat
  tags: asdf
  become: true
  become_user: "{{ asdf_user }}"

- name: Ensure .tool-versions
  file:
    path: "/home/{{ asdf_user }}/.tool-versions"
    state: touch
  tags: asdf
  when: asdf_tool_versions_stat.stat.exists == false
  become: true
  become_user: "{{ asdf_user }}"

- name: Source asdf for login shells
  lineinfile:
    path: /home/{{ asdf_user }}/.bashrc
    line: '. $HOME/.asdf/asdf.sh'
  tags: asdf
  become: true
  become_user: "{{ asdf_user }}"
