---
- include_tasks: node-deps-debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: node-deps-redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Node | Check if asdf-node is present
  shell: asdf plugin list | grep nodejs
  ignore_errors: yes
  register: asdf_node_present
  tags: node
  changed_when: false
  become: true
  become_user: "{{ asdf_user }}"

- name: Node | Install asdf nodejs plugin
  shell: asdf plugin add nodejs
  when: asdf_node_present is failed
  tags: node
  become: true
  become_user: "{{ asdf_user }}"

- name: Node | Check if nodejs version is present
  shell: asdf list nodejs | grep {{ asdf_nodejs_version }}
  ignore_errors: yes
  register: asdf_nodejs_version_present
  tags: node
  changed_when: false
  become: true
  become_user: "{{ asdf_user }}"

- name: Node | Install nodejs version
  shell: "asdf install nodejs {{ asdf_nodejs_version }}"
  when: asdf_nodejs_version_present is failed
  tags: node
  become: true
  become_user: "{{ asdf_user }}"

- name: Node | Set global version of nodejs
  lineinfile:
    path: "/home/{{ asdf_user }}/.tool-versions"
    line: 'nodejs {{ asdf_nodejs_version }}'
    regexp: '^nodejs '
  tags: node
  become: true
  become_user: "{{ asdf_user }}"
