---
- name: Ruby | install dependencies
  tags: ruby
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - git-core
      - zlib
      - zlib-devel
      - gcc-c++
      - patch
      - readline
      - readline-devel
      - libyaml-devel
      - libffi-devel
      - openssl-devel
      - make
      - bzip2
      - autoconf
      - automake
      - libtool
      - bison
      - curl
      - sqlite-devel
      - gdbm-devel
      - ncurses-devel
  become: true
